//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedSession
    {
        public int Id { get; set; }
        public System.DateTime EndDate { get; set; }
        public string ClientName { get; set; }
        public int CentreId { get; set; }
    
        public virtual Centre Centre { get; set; }
    }
}
